#!/bin/bash
echo "잠시 후 세팅이 시작됩니다"
sleep 3
echo "mariadb-server repo등록중..."
sleep 1
curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash -s -- --mariadb-server-version="mariadb-10.6"
sleep 1
echo "mariadb-server 버전이 10.6으로 등록되었습니다"
sleep 1
PACKAGES="httpd httpd-devel pcre-devel mod_ssl telnet-server tilix bind bind-utils php php-opcache php-gd php-curl php-mysqlnd mariadb-server mariadb wireshark mc vsftpd dhcp-server git"
echo "rocky linux의 업데이트를 시작합니다"
sleep 1
dnf update -y
echo "rocky linux의 업데이트가 완료되었습니다"
sleep 1
echo "잠시 후 패키지가 다운로드 됩니다"
echo "다운로드 되는 패키지는 http 관련파일, telnet, tilix, dns서버, php, mariadb, wireshark, vsftpd, dhcp-server, git 입니다"
sleep 1
dnf install -y epel-release
dnf install -y $PACKAGES
sleep 1
echo "selinux 정책이 설정됩니다"
sleep 1
setsebool -P ftpd_full_access on
setsebool -P ftpd_use_passive_mode 1
setsebool -P httpd_can_network_connect 1
setsebool -P httpd_read_user_content 1
setsebool -P httpd_can_network_connect_db 1
setsebool -P httpd_enable_homedirs 1
setsebool -P httpd_unified 1
setsebool -P domain_can_mmap_files 1
setsebool -P nis_enabled 1

update-crypto-policies --set LEGACY
echo "selinux 정책이 설정되고, selinux가 Permissive 상태로 임시 변경됩니다"
sleep 1
echo "방화벽에 http,https,mysql,dns,ftp,telnet가 추가됩니다"
sleep 1
firewall-cmd --permanent --add-service={http,https,mysql,dns,ftp,ssh,telnet}
firewall-cmd --reload
echo "현재 방화벽에서 오픈한 서비스들은"
firewall-cmd --list-services
echo "입니다"
sleep 1
dnf groupinstall -y "Xfce" "base-x"
echo "exec /usr/bin/xfce4-session" >> ~/.xinitrc

echo "dhcp.conf.example 파일이 /etc/dhcp/dhcpd.conf로 복사되어 저장됩니다"
cat /usr/share/doc/dhcp-server/dhcpd.conf.example | egrep -v "^#|^$" > /etc/dhcp/dhcpd.conf
sleep 1
echo "sshd, telnet.soket, vsftpd, named, httpd, mariadb가 재시작됩니다"
systemctl enable --now sshd telnet.socket vsftpd named httpd mariadb
sleep 1

echo "gnuboard와 DVWA, bWAAP, http의 기본 index(앵무새)파일이 다운로드 됩니다"
sleep 1
echo "github에서 파일을 불러옵니다..."
git clone https://github.com/Jong12s/httpd.git /var/www/html/backupa
sleep 1
yes | cp -r /var/www/html/backupa/* /var/www/html/
echo "github에서 파일이 다운로드 되었습니다"
sleep 1
rm -rf /var/www/html/backupa/
sleep 1
unzip -o /var/www/html/bWAPP.zip -d /var/www/html/
unzip -o /var/www/html/gnuboard.zip -d /var/www/html/
unzip -o /var/www/html/DVWA.zip -d /var/www/html/
unzip -o /var/www/html/PHP.zip -d /var/www/html/
unzip -o /var/www/html/mutillidae.zip -d /var/www/html/

chown -R apache:apache /var/www/html/
echo "mariadb에 gnuboard, dvwa, bWAPP,mutillidae, paddler, db_home, insecure 데이터베이스가 생성됩니다."
sleep 1
mysql -e "CREATE DATABASE IF NOT EXISTS gnuboard; \
          CREATE DATABASE IF NOT EXISTS dvwa; \
          CREATE DATABASE IF NOT EXISTS bWAPP; \
          CREATE DATABASE IF NOT EXISTS mutillidae; \
          CREATE DATABASE IF NOT EXISTS paddler; \
          CREATE DATABASE IF NOT EXISTS db_home;"
sleep 1
mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'adm'@'%' IDENTIFIED BY 'adm'; \
          GRANT ALL PRIVILEGES ON gnuboard.* TO 'gnu'@'%' IDENTIFIED BY 'gnu'; \
          GRANT ALL PRIVILEGES ON dvwa.* TO 'dvwa'@'%' IDENTIFIED BY 'dvwa'; \
          GRANT ALL PRIVILEGES ON bWAPP.* TO 'bwapp'@'%' IDENTIFIED BY 'bwapp'; \
          GRANT ALL PRIVILEGES ON mutillidae.* TO 'mutillidae'@'%' IDENTIFIED BY 'mutillidae'; \
          GRANT ALL PRIVILEGES ON paddler.* TO 'paddler'@'%' IDENTIFIED BY 'paddler'; \
          GRANT ALL PRIVILEGES ON db_home.* TO 'home'@'%' IDENTIFIED BY 'home'; \
          GRANT ALL PRIVILEGES ON insecure.* TO 'insecure'@'%' IDENTIFIED BY 'insecure'; \
          FLUSH PRIVILEGES;"
sleep 1
mysql db_home < /var/www/html/home/free/free.sql
mysql db_home < /var/www/html/home/free/free_ripple.sql
mysql db_home < /var/www/html/home/member/member.sql
mysql paddler < /var/www/html/paddler/free/db.sql
sleep 1
mysql -e "CREATE DATABASE IF NOT EXISTS insecure; \
          USE insecure; \
          CREATE TABLE IF NOT EXISTS members ( \
            idx INT NOT NULL AUTO_INCREMENT, \
            id VARCHAR(30), \
            password VARCHAR(100), \
            name VARCHAR(50), \
            email VARCHAR(30), \
            company VARCHAR(30), \
            PRIMARY KEY (idx) \
          ) DEFAULT CHARSET = utf8; \
          CREATE TABLE IF NOT EXISTS insecure_board ( \
            idx INT NOT NULL AUTO_INCREMENT, \
            title VARCHAR(50), \
            content TEXT, \
            id VARCHAR(20), \
            writer VARCHAR(30), \
            password VARCHAR(50), \
            file VARCHAR(50), \
            regdate DATE, \
            secret VARCHAR(2), \
            PRIMARY KEY (idx) \
          ) DEFAULT CHARSET = utf8; \
          CREATE TABLE IF NOT EXISTS customer_info ( \
            idx INT, \
            id VARCHAR(15), \
            password VARCHAR(30), \
            jumin VARCHAR(15) \
          ); \
          INSERT INTO customer_info VALUES (1, 'admin', '@dmin!q@w#e', '810203-1023113'); \
          INSERT INTO customer_info VALUES (2, 'gugucon', '99c0n', '861121-1244251'); \
          INSERT INTO customer_info VALUES (3, 'sonata_zzang', 'sosohan123', '890912-1601812'); \
          INSERT INTO customer_info VALUES (4, 'halls', 'halls920912', '921001-1881222'); \
          INSERT INTO customer_info VALUES (5, 'tkworld', '1q2w3e4r', '870405-1285264');"
sleep 1
ausearch -c 'php-fpm' --raw | audit2allow -M php-fpm-mysql-socket
sleep 1
semodule -i php-fpm-mysql-socket.pp
sleep 1
sed -i 's/short_open_tag = Off/short_open_tag = On/' /etc/php.ini
systemctl restart php-fpm
echo "mariadb에 모든 권한을 가진 adm계정이 생성됩니다. 비밀번호는 adm입니다"
sleep 1
echo "mariadb의 db명에 따라  모든 권한을 가진 계정이름'db', 비밀번호'db'가 생성됩니다. "
echo "예) gnuboard, gnu, gnu...  DVWA, dvwa, dvwa"
sleep 1
echo "bWAPP의 접속 기본 계정의 id는 bee, 비밀번호는 bug입니다."
echo "dvwa의 접속 기본계정의 id는 admin, 비밀번호는 password입니다."
echo "모든 설정들이 완료되었습니다."